//! Precomputes the risc0-Groth16 verifier-identity constants the covenant
//! redeem script bakes into its body, so the runtime crate doesn't need to
//! pull in `arkworks` / `risc0-groth16` for script construction.
//!
//! Emits `$OUT_DIR/groth16_consts.rs`, included by `script::groth16_consts`.
//!
//! Cross-tests in `script.rs` re-derive each constant at test time from
//! `risc0-groth16` / `risc0-zkvm` and assert byte-for-byte equality — so any
//! risc0 release that shifts these values will trip the test rather than
//! silently break the on-chain Groth16 precompile.
use std::{env, fs, path::Path};

use ark_bn254::Bn254;
use ark_groth16::VerifyingKey;
use ark_serialize::{CanonicalDeserialize, CanonicalSerialize};
use risc0_zkvm::{
    Groth16ReceiptVerifierParameters, SystemState,
    sha::{Digest, Digestible},
};
use sha2::{Digest as _, Sha256};

fn verifying_key_compressed() -> Vec<u8> {
    let vk_risc0 = risc0_groth16::verifying_key();
    let vk_bytes_prefixed_with_len = bincode::serialize(&vk_risc0).unwrap();
    // bincode prepends an 8-byte length tag; skip it.
    let vk = VerifyingKey::<Bn254>::deserialize_uncompressed(&mut &vk_bytes_prefixed_with_len[8..])
        .unwrap();
    let mut out = Vec::new();
    vk.serialize_compressed(&mut out).unwrap();
    out
}

fn split_digest(d: Digest) -> ([u8; 32], [u8; 32]) {
    const MID: usize = core::mem::size_of::<Digest>() / 2;
    let (first, second) = d.as_bytes().split_at(MID);
    let pad = |slice: &[u8]| {
        let mut scalar = [0u8; 32];
        scalar[..MID].copy_from_slice(slice);
        scalar
    };
    (pad(first), pad(second))
}

fn sha256_of(input: &[u8]) -> [u8; 32] {
    let mut hasher = Sha256::new();
    hasher.update(input);
    hasher.finalize().into()
}

fn fmt_array32(bytes: &[u8; 32]) -> String {
    let mut s = String::from("[");
    for (i, b) in bytes.iter().enumerate() {
        if i > 0 {
            s.push_str(", ");
        }
        s.push_str(&format!("0x{:02x}", b));
    }
    s.push(']');
    s
}

fn fmt_slice(bytes: &[u8]) -> String {
    let mut s = String::from("&[");
    for (i, b) in bytes.iter().enumerate() {
        if i > 0 {
            s.push_str(", ");
        }
        s.push_str(&format!("0x{:02x}", b));
    }
    s.push(']');
    s
}

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let params = Groth16ReceiptVerifierParameters::default();
    let bn254_control_id: [u8; 32] = params.bn254_control_id.into();
    let (control_root_a0, control_root_a1) = split_digest(params.control_root);

    let vk_compressed = verifying_key_compressed();

    let receipt_claim_tag = sha256_of(b"risc0.ReceiptClaim");
    let output_tag = sha256_of(b"risc0.Output");

    let post_digest: [u8; 32] =
        SystemState { pc: 0, merkle_root: Digest::ZERO }.digest().as_bytes().try_into().unwrap();

    let body = format!(
        "// Auto-generated by build.rs. Do not edit.\n\
         // Cross-tests in script.rs assert each constant matches the live\n\
         // risc0-groth16 / risc0-zkvm output, so a stale value fails noisily.\n\
         \n\
         pub const GROTH16_VK_COMPRESSED: &[u8] = {vk};\n\
         pub const GROTH16_BN254_CONTROL_ID: [u8; 32] = {bn254};\n\
         pub const GROTH16_CONTROL_ROOT_A0: [u8; 32] = {a0};\n\
         pub const GROTH16_CONTROL_ROOT_A1: [u8; 32] = {a1};\n\
         pub const RECEIPT_CLAIM_TAG_DIGEST: [u8; 32] = {rc};\n\
         pub const OUTPUT_TAG_DIGEST: [u8; 32] = {out};\n\
         pub const POST_DIGEST: [u8; 32] = {post};\n",
        vk = fmt_slice(&vk_compressed),
        bn254 = fmt_array32(&bn254_control_id),
        a0 = fmt_array32(&control_root_a0),
        a1 = fmt_array32(&control_root_a1),
        rc = fmt_array32(&receipt_claim_tag),
        out = fmt_array32(&output_tag),
        post = fmt_array32(&post_digest),
    );

    let out_dir = env::var_os("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("groth16_consts.rs");
    fs::write(&dest, body).expect("write groth16_consts.rs");
}
