//! Build script — precomputes the permission-tree empty-subtree hashes.
//!
//! `permission_tree`'s empty-subtree hash at level `L` is a pure constant: `sha256("PermEmpty")`
//! at level 0, `sha256("PermBranch" || h || h)` at each level up. Computing it in the
//! batch-processor guest costs `L` SHA-256 compressions per call; precomputing the whole
//! `0..=PERM_MAX_DEPTH` table here turns each guest use into an array read. Mirrors
//! `kaspa-smt`'s `build.rs`; `permission_tree`'s `empty_hashes_table_matches_runtime` test
//! revalidates this output against a runtime recomputation.

use std::{env, fs, path::Path};

use sha2::{Digest, Sha256};

/// Must match `permission_tree::PERM_MAX_DEPTH`. Drift is caught at compile time: the generated
/// array's length has to satisfy the `[[u8; 32]; PERM_MAX_DEPTH + 1]` type annotation on
/// `PERM_EMPTY_HASHES`.
const PERM_MAX_DEPTH: usize = 32;

/// `sha256("PermBranch" || left || right)` — mirrors `permission_tree::perm_branch_hash`.
fn branch(left: &[u8; 32], right: &[u8; 32]) -> [u8; 32] {
    let mut hasher = Sha256::new_with_prefix(b"PermBranch");
    hasher.update(left);
    hasher.update(right);
    hasher.finalize().into()
}

fn main() {
    let mut table = [[0u8; 32]; PERM_MAX_DEPTH + 1];
    table[0] = Sha256::new_with_prefix(b"PermEmpty").finalize().into();
    for level in 1..=PERM_MAX_DEPTH {
        table[level] = branch(&table[level - 1], &table[level - 1]);
    }

    let mut code = String::from("// @generated by build.rs — do not edit.\n[\n");
    for hash in &table {
        let bytes: Vec<String> = hash.iter().map(|b| format!("0x{b:02x}")).collect();
        code.push_str(&format!("    [{}],\n", bytes.join(", ")));
    }
    code.push_str("]\n");

    let dest = Path::new(&env::var("OUT_DIR").unwrap()).join("perm_empty_hashes_generated.rs");
    fs::write(dest, code).unwrap();
    println!("cargo::rerun-if-changed=build.rs");
}
