//! Build script. Precomputes the permission-tree empty-subtree hash table.
//!
//! Computing the table in the batch-processor guest would cost one hash per level per call;
//! precomputing it here turns each use into an array read. The runtime side cross-checks the
//! generated table against the runtime helper.

use std::{env, fs, path::Path};

use crate::config::Builder;

fn main() {
    let table = Builder::compute_empty_hashes();

    let mut code = String::from("// @generated by build.rs, do not edit.\n[\n");
    for hash in &table {
        let bytes: Vec<String> = hash.iter().map(|b| format!("0x{b:02x}")).collect();
        code.push_str(&format!("    [{}],\n", bytes.join(", ")));
    }
    code.push_str("]\n");

    let dest = Path::new(&env::var("OUT_DIR").unwrap()).join("perm_empty_hashes_generated.rs");
    fs::write(dest, code).unwrap();
    println!("cargo::rerun-if-changed=build.rs");
}

/// Type-level wiring duplicated from the runtime side so the build script can compute the
/// table without depending on the crate it's building.
mod config {
    use vprogs_core_hashing::Sha256;
    use vprogs_core_merkle_tree::{NodeTags, StreamingBuilder};

    pub(super) struct Tags;

    impl NodeTags<1> for Tags {
        const LEAF: &'static [u8; 1] = &[0x00];
        const BRANCH: &'static [u8; 1] = &[0x01];
        const EMPTY: &'static [u8; 1] = &[0x02];
    }

    pub(super) type Builder = StreamingBuilder<Sha256, Tags, 32, 1>;
}
