//! Build script. Precomputes the permission-tree empty-subtree hash table.
//!
//! Computing the table in the batch-processor guest would cost one hash per level per call;
//! precomputing it here turns each use into an array read. The runtime side cross-checks the
//! generated table against the runtime helper.

use std::{env, fs, path::Path};

use vprogs_core_merkle_tree::StreamingBuilder;

use crate::permission_tags::PermTags;

/// Shared domain-tag source, `include!`d so the build-time table and the runtime accumulator
/// compute against one definition (see `permission_tags.rs`).
#[path = "src/permission_tags.rs"]
mod permission_tags;

fn main() {
    let table =
        StreamingBuilder::<vprogs_core_hashing::Sha256, PermTags, 32, 1>::compute_empty_hashes();

    let mut code = String::from("// @generated by build.rs, do not edit.\n[\n");
    for hash in &table {
        let bytes: Vec<String> = hash.iter().map(|b| format!("0x{b:02x}")).collect();
        code.push_str(&format!("    [{}],\n", bytes.join(", ")));
    }
    code.push_str("]\n");

    let dest = Path::new(&env::var("OUT_DIR").unwrap()).join("perm_empty_hashes_generated.rs");
    fs::write(dest, code).unwrap();
    println!("cargo::rerun-if-changed=build.rs");
    println!("cargo::rerun-if-changed=src/permission_tags.rs");
}
